-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "widthCm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "heightCm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lengthCm" SET DATA TYPE DOUBLE PRECISION;
